name: Create Release and Upload Build Artifacts

on:
  release:
    types:
      - created

jobs:
  build-and-release:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore TileBakeTool/TileBakeTool.csproj

    - name: Build
      run: dotnet build TileBakeTool/TileBakeTool.csproj --no-restore

    - name: Test
      run: dotnet test TileBakeTool/TileBakeTool.csproj --no-build --verbosity normal

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          TileBakeTool/TileBakeTool.csproj   # Add more files/directories here if needed
        token: ${{ secrets.GITHUB_TOKEN }}
