# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore TileBakeTool/TileBakeTool.csproj

    - name: Build Release
      run: | 
        if [ "$RUNNER_OS" == "Windows" ]; then
          dotnet build TileBakeTool/TileBakeTool.csproj --configuration --verbosity normal Release --output ./windows-publish
        elif [ "$RUNNER_OS" == "Linux" ]; then
          dotnet build TileBakeTool/TileBakeTool.csproj --configuration --verbosity normal Release --output ./linux-publish
        else
          dotnet build TileBakeTool/TileBakeTool.csproj --configuration --verbosity normal Release --output ./macos-publish
        fi
    
    - name: Publish Windows Artifacts
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v2
      with:
        name: windows-artifacts
        path: ./windows-publish

    - name: Publish Linux Artifacts
      if: runner.os == 'Linux'
      uses: actions/upload-artifact@v2
      with:
        name: linux-artifacts
        path: ./linux-publish

    - name: Publish macOS Artifacts
      if: runner.os == 'macOS'
      uses: actions/upload-artifact@v2
      with:
        name: macos-artifacts
        path: ./macos-publish
